### PR TITLE
Fixes for PR issues

### LINKED ISSUE #15: Fix PR issues
- Add alias for neetoIcons.
- Refactor Card component to compound component.
- Refactor MenuBar component.
- Remove required keyword from Form component.
- Rename NewNotePane, ContactMenuBar, Pane and ContactTable components.
- Refactor icons with Neeto icons.
- Remove prop-types.
- Rename function name.

### PR DESCRIPTION
**Pull request by Thejus-Paul**
Fixes #15 
- Added alias for neetoIcons.
- Refactored Card component to compound component.
- Refactored MenuBar component.
- Removed required keyword from Form component.
- Renamed NewNotePane, ContactMenuBar, Pane and ContactTable components.
- Refactored icons with Neeto icons.
- Removed prop-types.
- Renamed function name.

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/Card/index.jsx [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+}) => {
+  const handleDelete = () => setNoteIdToDelete(id);
+
+  const createdTime = dayjs(created_at);
+  const getTimeDiffInHours = dayjs().hour() - createdTime.hour();
+
+  return (
+    <NoteCard>
+      <NoteCard.Header title={title} handleDelete={handleDelete} />
+      <NoteCard.Body description={description} />
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/Card/index.jsx]: Let's pass `description` as `children` here. That would provide more flexibility to the component.

**Review by karthiknmenon — CHANGES_REQUESTED** [review]
@Thejus-Paul One minor suggestion. The rest looks good.

**Review by karthiknmenon — APPROVED** [review]
